FROM summerwind/actions-runner-dind:${LATEST_RUNNER_VERSION}

USER root

ENV NODE_VERSION 20.12.1

RUN apt-get update \
    && apt-get install xz-utils curl wget -y

RUN wget -q https://github.com/qa-guru/allure-notifications/releases/download/4.3.0/allure-notifications-4.3.0.jar -O /home/runner/notifications.jar
    
RUN curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64.tar.xz" \
    && tar -xJf "node-v$NODE_VERSION-linux-x64.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
    && rm "node-v$NODE_VERSION-linux-x64.tar.xz" \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    && node -v
RUN npm install @playwright/test -g
RUN npx playwright install-deps \
    && npx playwright install

RUN chown -R runner:runner "/home/runner/.npm"

USER runner

LABEL org.opencontainers.image.source https://github.com/daymarket/qa-docker