FROM summerwind/actions-runner-dind:${LATEST_RUNNER_VERSION}

USER root

RUN curl -s https://repos.azul.com/azul-repo.key | gpg --dearmor -o /usr/share/keyrings/azul.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/azul.gpg] https://repos.azul.com/zulu/deb stable main" | tee /etc/apt/sources.list.d/zulu.list && \
    apt update && \
    apt install zulu17-jdk -y
    
RUN apt install wget -y

USER runner

LABEL org.opencontainers.image.source https://github.com/daymarket/qa-docker